import type { Result } from '@/types/common'
import type { WsConnectResult, WsIncoming, WsStateEvent } from '@/types/websocket'

export interface WsConnectReq {
  requestId: string
  workspaceId: string
  // Generated by the store so it can subscribe before the handshake starts.
  connectionId: string
}

export interface WsSendReq {
  connectionId: string
  data: string
  messageType: 'text' | 'binary'
}

export interface WebSocketServiceAPI {
  connect(req: WsConnectReq): Promise<Result<WsConnectResult>>
  send(req: WsSendReq): Promise<Result<Record<string, never>>>
  disconnect(req: { connectionId: string }): Promise<Result<Record<string, never>>>
  // subscribe wires inbound message + state handlers; returns an unsubscribe fn.
  subscribe(
    connectionId: string,
    handlers: { onMessage: (m: WsIncoming) => void; onState: (s: WsStateEvent) => void },
  ): Promise<() => void>
}
